<table width="720" align="CENTER"  width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
	<tr valign=TOP>
	  <td height="43" COLSPAN=2><img src="../images/top.jpg" width="720" height="48"></td>
	</tr>
	<tr valign=TOP>
	  <td align="LEFT" class="Estilo37">Usuario: <%=UCASE(session("nombre_user"))%></td>
	  <td align="RIGHT" class="Estilo37">
		  <a href="scg_web.asp">PRINCIPAL</a> |
		  <a href="#" onClick='javascript:history.back()'>VOLVER</a> |
		  <a href="cbdd02.asp"><acronym title="SALIR DEL SISTEMA">CERRAR SESI&Oacute;N</acronym></a>
	  </td>
	</tr>
</table>